/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */
#ifndef OCEANBASE_UNITTEST_SQL_ENGINE_BASIC_UTILS_MOCK_CHILD_H_
#define OCEANBASE_UNITTEST_SQL_ENGINE_BASIC_UTILS_MOCK_CHILD_H_

#include <gtest/gtest.h>
#include <vector>
#include "sql/engine/ob_operator.h"
#include "sql/engine/ob_exec_context.h"
#include "expr_maker.h"

namespace oceanbase
{
namespace sql
{
class ObPhysicalPlan;

// Minimal spec for the mock child operator used by basic operator UTs.
class MockChildSpec : public ObOpSpec
{
public:
  explicit MockChildSpec(common::ObIAllocator &alloc)
      : ObOpSpec(alloc, static_cast<ObPhyOperatorType>(0))
  {}
};

// Mock child operator that feeds vector batches generated by GenExprMaker list.
// gen() sets brs.size_, brs.end_, skip, all_rows_active.
// Keep one eval_ctx source inside operator so clear_evaluated_flag() and gen()
// always operate on the same frame and eval-info memory.
class MockChildOp : public ObOperator
{
public:
  MockChildOp(ObExecContext &exec_ctx, const ObOpSpec &spec, ObOpInput *input,
              const std::vector<GenExprMaker *> &gen_expr_makers,
              ObEvalCtx *eval_ctx_ref = nullptr)
      : ObOperator(exec_ctx, spec, input),
        gen_expr_makers_(gen_expr_makers),
        eval_ctx_ref_(eval_ctx_ref)
  {}

  int inner_open() override { return OB_SUCCESS; }
  int inner_get_next_row() override { return OB_NOT_IMPLEMENT; }
  int inner_get_next_batch(const int64_t max_row_cnt) override;
  void set_parent_eval_ctx(ObEvalCtx *parent_eval_ctx) { parent_eval_ctx_ref_ = parent_eval_ctx; }
  void destroy() override { ObOperator::destroy(); }

private:
  std::vector<GenExprMaker *> gen_expr_makers_;
  std::vector<int64_t> skip_words_;
  ObEvalCtx *eval_ctx_ref_;
  ObEvalCtx *parent_eval_ctx_ref_ = nullptr;
};

// Utility wrapper for building and wiring one mock child into parent operator.
class MockChildUtils
{
public:
  MockChildUtils(ObExecContext &exec_ctx, ObEvalCtx &eval_ctx)
      : exec_ctx_(exec_ctx),
        eval_ctx_(eval_ctx),
        child_spec_arr_{nullptr},
        child_op_arr_{nullptr},
        spec_(exec_ctx.get_allocator()),
        op_(nullptr)
  {}

  void init(const int64_t batch_size,
            const std::vector<GenExprMaker *> &gen_expr_makers);
  // Attach prepared mock child spec/op to one parent node.
  void attach_to_parent(ObOpSpec &parent_spec, ObOperator &parent_op);
  void bind_plan(ObPhysicalPlan &phy_plan) { spec_.plan_ = &phy_plan; }

  MockChildSpec *spec() { return &spec_; }
  const MockChildSpec *spec() const { return &spec_; }
  MockChildOp *op() const { return op_; }

private:
  ObExecContext &exec_ctx_;
  ObEvalCtx &eval_ctx_;
  ObOpSpec *child_spec_arr_[1];
  ObOperator *child_op_arr_[1];
  MockChildSpec spec_;
  MockChildOp *op_;
};

} // namespace sql
} // namespace oceanbase

#endif // OCEANBASE_UNITTEST_SQL_ENGINE_BASIC_UTILS_MOCK_CHILD_H_
