/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#ifdef OB_OBJ_PRIV_TYPE_DEF
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_NONE, "")            // 0
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ALTER, "ALTER")      // 1
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_AUDIT, "AUDIT")      // 2
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_COMMENT, "COMMENT")  // 3
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DELETE, "DELETE")    // 4
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_GRANT, "GRANT")      // 5

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_INDEX, "INDEX")            // 6
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_INSERT, "INSERT")          // 7
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_LOCK, "LOCK")              // 8
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_RENAME, "RENAME")          // 9
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_SELECT, "SELECT")          // 10
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_UPDATE, "UPDATE")          // 11
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_REFERENCES, "REFERENCES")  // 12
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_EXECUTE, "EXECUTE")        // 13
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_CREATE, "CREATE")          // 14

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_FLASHBACK, "FLASHBACK")  // 15

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_READ, "READ")    // 16
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_WRITE, "WRITE")  // 17

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DEBUG, "DEBUG")              // 18
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_USE_CATALOG, "USE CATALOG")  // 19
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_PLAINACCESS, "PLAINACCESS")  // 20
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_MAX, "")
#endif

/* to do, No! May be no do forever. */
#ifdef asfasgasgfa 

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ENQUEUE, "ENQUEUE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_DEQUEUE, "DEQUEUE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_UNDER, "UNDER")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_ON_COMMIT_REFRESH, "ON COMMIT REFRESH")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_QUERY_REWRITE, "QUERY REWRITE")
/* index */
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_MERGE_VIEW, "MERGE VIEW")

OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_USE, "USE")
OB_OBJ_PRIV_TYPE_DEF(OBJ_PRIV_ID_FLASHBACK_ARCHIVE, "FLASHBACK ARCHIVE")

#endif

#ifndef OCEANBASE_SHARE_SCHEMA_OB_OBJ_PRIV_TYPE_
#define OCEANBASE_SHARE_SCHEMA_OB_OBJ_PRIV_TYPE_

enum OB_RAW_OBJ_PRIV_ID 
{
#define OB_OBJ_PRIV_TYPE_DEF(priv_id, priv_name) priv_id,
#include "share/schema/ob_obj_priv_type.h"
#undef OB_OBJ_PRIV_TYPE_DEF

};

#endif /* OB_OBJ_PRIV_TYPE_ */
