/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ob_pl_java_udf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ob_pl_java_udf.pb-c.h"
void   ob_pl__java_udf__batched_args__init
                     (ObPl__JavaUdf__BatchedArgs         *message)
{
  static const ObPl__JavaUdf__BatchedArgs init_value = OB_PL__JAVA_UDF__BATCHED_ARGS__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__batched_args__get_packed_size
                     (const ObPl__JavaUdf__BatchedArgs *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__batched_args__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__batched_args__pack
                     (const ObPl__JavaUdf__BatchedArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__batched_args__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__batched_args__pack_to_buffer
                     (const ObPl__JavaUdf__BatchedArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__batched_args__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__BatchedArgs *
       ob_pl__java_udf__batched_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__BatchedArgs *)
     protobuf_c_message_unpack (&ob_pl__java_udf__batched_args__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__batched_args__free_unpacked
                     (ObPl__JavaUdf__BatchedArgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__batched_args__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__values__init
                     (ObPl__JavaUdf__Values         *message)
{
  static const ObPl__JavaUdf__Values init_value = OB_PL__JAVA_UDF__VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__values__get_packed_size
                     (const ObPl__JavaUdf__Values *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__values__pack
                     (const ObPl__JavaUdf__Values *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__values__pack_to_buffer
                     (const ObPl__JavaUdf__Values *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__Values *
       ob_pl__java_udf__values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__Values *)
     protobuf_c_message_unpack (&ob_pl__java_udf__values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__values__free_unpacked
                     (ObPl__JavaUdf__Values *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__byte_values__init
                     (ObPl__JavaUdf__ByteValues         *message)
{
  static const ObPl__JavaUdf__ByteValues init_value = OB_PL__JAVA_UDF__BYTE_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__byte_values__get_packed_size
                     (const ObPl__JavaUdf__ByteValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__byte_values__pack
                     (const ObPl__JavaUdf__ByteValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__byte_values__pack_to_buffer
                     (const ObPl__JavaUdf__ByteValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__ByteValues *
       ob_pl__java_udf__byte_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__ByteValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__byte_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__byte_values__free_unpacked
                     (ObPl__JavaUdf__ByteValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__byte_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__short_values__init
                     (ObPl__JavaUdf__ShortValues         *message)
{
  static const ObPl__JavaUdf__ShortValues init_value = OB_PL__JAVA_UDF__SHORT_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__short_values__get_packed_size
                     (const ObPl__JavaUdf__ShortValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__short_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__short_values__pack
                     (const ObPl__JavaUdf__ShortValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__short_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__short_values__pack_to_buffer
                     (const ObPl__JavaUdf__ShortValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__short_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__ShortValues *
       ob_pl__java_udf__short_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__ShortValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__short_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__short_values__free_unpacked
                     (ObPl__JavaUdf__ShortValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__short_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__int_values__init
                     (ObPl__JavaUdf__IntValues         *message)
{
  static const ObPl__JavaUdf__IntValues init_value = OB_PL__JAVA_UDF__INT_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__int_values__get_packed_size
                     (const ObPl__JavaUdf__IntValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__int_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__int_values__pack
                     (const ObPl__JavaUdf__IntValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__int_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__int_values__pack_to_buffer
                     (const ObPl__JavaUdf__IntValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__int_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__IntValues *
       ob_pl__java_udf__int_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__IntValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__int_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__int_values__free_unpacked
                     (ObPl__JavaUdf__IntValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__int_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__long_values__init
                     (ObPl__JavaUdf__LongValues         *message)
{
  static const ObPl__JavaUdf__LongValues init_value = OB_PL__JAVA_UDF__LONG_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__long_values__get_packed_size
                     (const ObPl__JavaUdf__LongValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__long_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__long_values__pack
                     (const ObPl__JavaUdf__LongValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__long_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__long_values__pack_to_buffer
                     (const ObPl__JavaUdf__LongValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__long_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__LongValues *
       ob_pl__java_udf__long_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__LongValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__long_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__long_values__free_unpacked
                     (ObPl__JavaUdf__LongValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__long_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__float_values__init
                     (ObPl__JavaUdf__FloatValues         *message)
{
  static const ObPl__JavaUdf__FloatValues init_value = OB_PL__JAVA_UDF__FLOAT_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__float_values__get_packed_size
                     (const ObPl__JavaUdf__FloatValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__float_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__float_values__pack
                     (const ObPl__JavaUdf__FloatValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__float_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__float_values__pack_to_buffer
                     (const ObPl__JavaUdf__FloatValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__float_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__FloatValues *
       ob_pl__java_udf__float_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__FloatValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__float_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__float_values__free_unpacked
                     (ObPl__JavaUdf__FloatValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__float_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__double_values__init
                     (ObPl__JavaUdf__DoubleValues         *message)
{
  static const ObPl__JavaUdf__DoubleValues init_value = OB_PL__JAVA_UDF__DOUBLE_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__double_values__get_packed_size
                     (const ObPl__JavaUdf__DoubleValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__double_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__double_values__pack
                     (const ObPl__JavaUdf__DoubleValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__double_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__double_values__pack_to_buffer
                     (const ObPl__JavaUdf__DoubleValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__double_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__DoubleValues *
       ob_pl__java_udf__double_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__DoubleValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__double_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__double_values__free_unpacked
                     (ObPl__JavaUdf__DoubleValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__double_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__big_decimal_values__init
                     (ObPl__JavaUdf__BigDecimalValues         *message)
{
  static const ObPl__JavaUdf__BigDecimalValues init_value = OB_PL__JAVA_UDF__BIG_DECIMAL_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__big_decimal_values__get_packed_size
                     (const ObPl__JavaUdf__BigDecimalValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__big_decimal_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__big_decimal_values__pack
                     (const ObPl__JavaUdf__BigDecimalValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__big_decimal_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__big_decimal_values__pack_to_buffer
                     (const ObPl__JavaUdf__BigDecimalValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__big_decimal_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__BigDecimalValues *
       ob_pl__java_udf__big_decimal_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__BigDecimalValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__big_decimal_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__big_decimal_values__free_unpacked
                     (ObPl__JavaUdf__BigDecimalValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__big_decimal_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__string_values__init
                     (ObPl__JavaUdf__StringValues         *message)
{
  static const ObPl__JavaUdf__StringValues init_value = OB_PL__JAVA_UDF__STRING_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__string_values__get_packed_size
                     (const ObPl__JavaUdf__StringValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__string_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__string_values__pack
                     (const ObPl__JavaUdf__StringValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__string_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__string_values__pack_to_buffer
                     (const ObPl__JavaUdf__StringValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__string_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__StringValues *
       ob_pl__java_udf__string_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__StringValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__string_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__string_values__free_unpacked
                     (ObPl__JavaUdf__StringValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__string_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ob_pl__java_udf__byte_buffer_values__init
                     (ObPl__JavaUdf__ByteBufferValues         *message)
{
  static const ObPl__JavaUdf__ByteBufferValues init_value = OB_PL__JAVA_UDF__BYTE_BUFFER_VALUES__INIT;
  *message = init_value;
}
size_t ob_pl__java_udf__byte_buffer_values__get_packed_size
                     (const ObPl__JavaUdf__ByteBufferValues *message)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_buffer_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ob_pl__java_udf__byte_buffer_values__pack
                     (const ObPl__JavaUdf__ByteBufferValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_buffer_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ob_pl__java_udf__byte_buffer_values__pack_to_buffer
                     (const ObPl__JavaUdf__ByteBufferValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ob_pl__java_udf__byte_buffer_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObPl__JavaUdf__ByteBufferValues *
       ob_pl__java_udf__byte_buffer_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObPl__JavaUdf__ByteBufferValues *)
     protobuf_c_message_unpack (&ob_pl__java_udf__byte_buffer_values__descriptor,
                                allocator, len, data);
}
void   ob_pl__java_udf__byte_buffer_values__free_unpacked
                     (ObPl__JavaUdf__ByteBufferValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ob_pl__java_udf__byte_buffer_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ob_pl__java_udf__batched_args__field_descriptors[2] =
{
  {
    "batch_size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(ObPl__JavaUdf__BatchedArgs, batch_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__BatchedArgs, n_args),
    offsetof(ObPl__JavaUdf__BatchedArgs, args),
    &ob_pl__java_udf__values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__batched_args__field_indices_by_name[] = {
  1,   /* field[1] = args */
  0,   /* field[0] = batch_size */
};
static const ProtobufCIntRange ob_pl__java_udf__batched_args__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__batched_args__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.BatchedArgs",
  "BatchedArgs",
  "ObPl__JavaUdf__BatchedArgs",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__BatchedArgs),
  2,
  ob_pl__java_udf__batched_args__field_descriptors,
  ob_pl__java_udf__batched_args__field_indices_by_name,
  1,  ob_pl__java_udf__batched_args__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__batched_args__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__values__field_descriptors[10] =
{
  {
    "null_map",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ObPl__JavaUdf__Values, null_map),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "byte_values",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, byte_values),
    &ob_pl__java_udf__byte_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "short_values",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, short_values),
    &ob_pl__java_udf__short_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_values",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, int_values),
    &ob_pl__java_udf__int_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_values",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, long_values),
    &ob_pl__java_udf__long_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_values",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, float_values),
    &ob_pl__java_udf__float_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_values",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, double_values),
    &ob_pl__java_udf__double_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "big_decimal_values",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, big_decimal_values),
    &ob_pl__java_udf__big_decimal_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_values",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, string_values),
    &ob_pl__java_udf__string_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "byte_buffer_values",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObPl__JavaUdf__Values, values_case),
    offsetof(ObPl__JavaUdf__Values, byte_buffer_values),
    &ob_pl__java_udf__byte_buffer_values__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__values__field_indices_by_name[] = {
  7,   /* field[7] = big_decimal_values */
  9,   /* field[9] = byte_buffer_values */
  1,   /* field[1] = byte_values */
  6,   /* field[6] = double_values */
  5,   /* field[5] = float_values */
  3,   /* field[3] = int_values */
  4,   /* field[4] = long_values */
  0,   /* field[0] = null_map */
  2,   /* field[2] = short_values */
  8,   /* field[8] = string_values */
};
static const ProtobufCIntRange ob_pl__java_udf__values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.Values",
  "Values",
  "ObPl__JavaUdf__Values",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__Values),
  10,
  ob_pl__java_udf__values__field_descriptors,
  ob_pl__java_udf__values__field_indices_by_name,
  1,  ob_pl__java_udf__values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__byte_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ObPl__JavaUdf__ByteValues, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__byte_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__byte_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__byte_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.ByteValues",
  "ByteValues",
  "ObPl__JavaUdf__ByteValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__ByteValues),
  1,
  ob_pl__java_udf__byte_values__field_descriptors,
  ob_pl__java_udf__byte_values__field_indices_by_name,
  1,  ob_pl__java_udf__byte_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__byte_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__short_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(ObPl__JavaUdf__ShortValues, n_value),
    offsetof(ObPl__JavaUdf__ShortValues, value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__short_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__short_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__short_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.ShortValues",
  "ShortValues",
  "ObPl__JavaUdf__ShortValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__ShortValues),
  1,
  ob_pl__java_udf__short_values__field_descriptors,
  ob_pl__java_udf__short_values__field_indices_by_name,
  1,  ob_pl__java_udf__short_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__short_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__int_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(ObPl__JavaUdf__IntValues, n_value),
    offsetof(ObPl__JavaUdf__IntValues, value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__int_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__int_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__int_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.IntValues",
  "IntValues",
  "ObPl__JavaUdf__IntValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__IntValues),
  1,
  ob_pl__java_udf__int_values__field_descriptors,
  ob_pl__java_udf__int_values__field_indices_by_name,
  1,  ob_pl__java_udf__int_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__int_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__long_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SFIXED64,
    offsetof(ObPl__JavaUdf__LongValues, n_value),
    offsetof(ObPl__JavaUdf__LongValues, value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__long_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__long_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__long_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.LongValues",
  "LongValues",
  "ObPl__JavaUdf__LongValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__LongValues),
  1,
  ob_pl__java_udf__long_values__field_descriptors,
  ob_pl__java_udf__long_values__field_indices_by_name,
  1,  ob_pl__java_udf__long_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__long_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__float_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ObPl__JavaUdf__FloatValues, n_value),
    offsetof(ObPl__JavaUdf__FloatValues, value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__float_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__float_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__float_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.FloatValues",
  "FloatValues",
  "ObPl__JavaUdf__FloatValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__FloatValues),
  1,
  ob_pl__java_udf__float_values__field_descriptors,
  ob_pl__java_udf__float_values__field_indices_by_name,
  1,  ob_pl__java_udf__float_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__float_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__double_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(ObPl__JavaUdf__DoubleValues, n_value),
    offsetof(ObPl__JavaUdf__DoubleValues, value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__double_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__double_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__double_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.DoubleValues",
  "DoubleValues",
  "ObPl__JavaUdf__DoubleValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__DoubleValues),
  1,
  ob_pl__java_udf__double_values__field_descriptors,
  ob_pl__java_udf__double_values__field_indices_by_name,
  1,  ob_pl__java_udf__double_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__double_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__big_decimal_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ObPl__JavaUdf__BigDecimalValues, n_value),
    offsetof(ObPl__JavaUdf__BigDecimalValues, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__big_decimal_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__big_decimal_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__big_decimal_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.BigDecimalValues",
  "BigDecimalValues",
  "ObPl__JavaUdf__BigDecimalValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__BigDecimalValues),
  1,
  ob_pl__java_udf__big_decimal_values__field_descriptors,
  ob_pl__java_udf__big_decimal_values__field_indices_by_name,
  1,  ob_pl__java_udf__big_decimal_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__big_decimal_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__string_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ObPl__JavaUdf__StringValues, n_value),
    offsetof(ObPl__JavaUdf__StringValues, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__string_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__string_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__string_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.StringValues",
  "StringValues",
  "ObPl__JavaUdf__StringValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__StringValues),
  1,
  ob_pl__java_udf__string_values__field_descriptors,
  ob_pl__java_udf__string_values__field_indices_by_name,
  1,  ob_pl__java_udf__string_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__string_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ob_pl__java_udf__byte_buffer_values__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ObPl__JavaUdf__ByteBufferValues, n_value),
    offsetof(ObPl__JavaUdf__ByteBufferValues, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ob_pl__java_udf__byte_buffer_values__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange ob_pl__java_udf__byte_buffer_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ob_pl__java_udf__byte_buffer_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ob_pl.java_udf.ByteBufferValues",
  "ByteBufferValues",
  "ObPl__JavaUdf__ByteBufferValues",
  "ob_pl.java_udf",
  sizeof(ObPl__JavaUdf__ByteBufferValues),
  1,
  ob_pl__java_udf__byte_buffer_values__field_descriptors,
  ob_pl__java_udf__byte_buffer_values__field_indices_by_name,
  1,  ob_pl__java_udf__byte_buffer_values__number_ranges,
  (ProtobufCMessageInit) ob_pl__java_udf__byte_buffer_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
