/**
 * Copyright (c) 2021 OceanBase
 * SPDX-License-Identifier: Apache-2.0
 */

// define the feature list here whose behavior is different in MySQL5.7, MySQL8.0 or OB
// DEF_COMPAT_CONTROL_FEATURE(type, id, is_dynamic, description, latest_version, patch_versions ...)
// then use ObBasicSessionInfo::check_feature_enable to check if the feature is enabled

#ifdef DEF_COMPAT_CONTROL_FEATURE
DEF_COMPAT_CONTROL_FEATURE(MYSQL_PRIV_ENHANCE, "add privilege check to some command",
    MOCK_CLUSTER_VERSION_4_2_3_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_2_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_SET_VAR_PRIV_ENHANCE, "check privilege for set var subquery",
    MOCK_CLUSTER_VERSION_4_2_4_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_2_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_USER_REVOKE_ALL_ENHANCE, "use create_user to check privilege for revoke all from user",
    MOCK_CLUSTER_VERSION_4_2_4_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_2_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_LOCK_TABLES_PRIV_ENHANCE, "add privilege for lock tables",
    MOCK_CLUSTER_VERSION_4_2_5_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_5_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_USER_REVOKE_ALL_WITH_PL_PRIV_CHECK, "revoke all on db.* need check pl privilege",
    MOCK_CLUSTER_VERSION_4_2_4_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_2_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_REFERENCES_PRIV_ENHANCE, "add privilege check to references",
    MOCK_CLUSTER_VERSION_4_2_4_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_3_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_TRIGGER_PRIV_CHECK, "add trigger privilege check",
    MOCK_CLUSTER_VERSION_4_2_4_0, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_3_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_EVENT_PRIV_CHECK, "add event privilege check",
    MOCK_CLUSTER_VERSION_4_2_5_2, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_5_2)
DEF_COMPAT_CONTROL_FEATURE(ORACLE_INSERT_ALL_PRIV_CHECK, "insert all privilege check",
    MOCK_CLUSTER_VERSION_4_2_5_5, CLUSTER_VERSION_4_3_0_0,
    MOCK_CLUSTER_VERSION_4_3_5_3)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_SHOW_CREATE_PROCEDURE_PRIV_CHECK, "add show create procedure privilege check",
    MOCK_CLUSTER_VERSION_4_2_5_3, CLUSTER_VERSION_4_3_0_0,
    CLUSTER_VERSION_4_3_5_2)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_CTE_PRIV_CHECK, "add CTE privilege check",
    MOCK_CLUSTER_VERSION_4_2_5_8, CLUSTER_VERSION_4_3_0_0,
    MOCK_CLUSTER_VERSION_4_3_5_5, CLUSTER_VERSION_4_4_0_0,
    MOCK_CLUSTER_VERSION_4_4_2_1, CLUSTER_VERSION_4_5_0_0,
    CLUSTER_VERSION_4_6_0_0)
DEF_COMPAT_CONTROL_FEATURE(ORACLE_UTL_NETWORK_PKG_PRIV_CHECK,
    "require EXECUTE privilege on UTL_TCP/UTL_HTTP/UTL_SMTP",
    MOCK_CLUSTER_VERSION_4_4_2_2, CLUSTER_VERSION_4_5_0_0,
    CLUSTER_VERSION_4_6_1_0)
DEF_COMPAT_CONTROL_FEATURE(MYSQL_VIEW_DEFINER_PRIV_CHECK_ENHANCE, "enable mysql view definer privilege check",
    CLUSTER_VERSION_4_6_1_0)

#endif
