/**
 * Copyright (c) 2021 OceanBase
 * SPDX-License-Identifier: Apache-2.0
 */

#define USING_LOG_PREFIX SHARE
#include "ob_storage_ha_diagnose_struct.h"

namespace oceanbase
{
namespace share
{

const char *const ObStorageDiagModuleStr[] = {
    "TRANSFER_ERROR_DIAGNOSE",
    "TRANSFER_PERF_DIAGNOSE",
};

const char *const ObStorageDiagTaskTypeStr[] = {
    "TRANSFER_START",
    "TRANSFER_DOING",
    "TRANSFER_ABORT",
    "TRANSFER_START_IN",
    "TRANSFER_START_OUT",
    "TRANSFER_FINISH_IN",
    "TRANSFER_FINISH_OUT",
    "TRANSFER_BACKFILLED",
};

const char *ha_diag_task_type_str(const ObStorageHADiagTaskType t)
{
  return is_valid_ha_diag_task_type(t)
      ? ObStorageDiagTaskTypeStr[static_cast<uint8_t>(t)]
      : "INVALID";
}

const char *const ObStorageHACostItemNameStr[] = {
  "TRANSFER_START_BEGIN",
  "LOCK_MEMBER_LIST",
  "PRECHECK_LS_REPALY_SCN",
  "CHECK_START_STATUS_TRANSFER_TABLETS",
  "CHECK_SRC_LS_HAS_ACTIVE_TRANS",
  "UPDATE_ALL_TABLET_TO_LS",
  "LOCK_TABLET_ON_DEST_LS_FOR_TABLE_LOCK",
  "BLOCK_AND_KILL_TX",
  "REGISTER_TRANSFER_START_OUT",
  "DEST_LS_GET_START_SCN",
  "UNBLOCK_TX",
  "WAIT_SRC_LS_REPLAY_TO_START_SCN",
  "SRC_LS_GET_TABLET_META",
  "REGISTER_TRANSFER_START_IN",
  "START_TRANS_COMMIT",
  "TRANSFER_START_END",
  "TRANSFER_FINISH_BEGIN",
  "UNLOCK_SRC_AND_DEST_LS_MEMBER_LIST",
  "CHECK_LS_LOGICAL_TABLE_REPLACED",
  "LOCK_LS_MEMBER_LIST_IN_DOING",
  "CHECK_LS_LOGICAL_TABLE_REPLACED_LATER",
  "REGISTER_TRANSFER_FINISH_IN",
  "WAIT_TRANSFER_TABLET_STATUS_NORMAL",
  "WAIT_ALL_LS_REPLICA_REPLAY_FINISH_SCN",
  "REGISTER_TRANSFER_OUT",
  "UNLOCK_TABLET_FOR_LOCK",
  "UNLOCK_LS_MEMBER_LIST",
  "FINISH_TRANS_COMMIT",
  "TRANSFER_FINISH_END",
  "TRANSFER_ABORT_BEGIN",
  "UNLOCK_MEMBER_LIST_IN_ABORT",
  "ABORT_TRANS_COMMIT",
  "TRANSFER_ABORT_END",
  "TRANSFER_BACKFILLED_TABLE_BEGIN",
  "TX_BACKFILL",
  "UNLOCK_MEMBER_LIST_IN_START",
  "ON_REGISTER_SUCCESS",
  "ON_REPLAY_SUCCESS",
  "TRANSFER_REPLACE_BEGIN",
  "TRANSFER_REPLACE_END",
  "TRANSFER_BACKFILL_START",
  "STOP_LS_SCHEDULE_MEMDIUM",
};

const char *const ObTransferErrorDiagMsg[] = {
  "TRANSFER_START_BEGIN_ERROR",
  "LOCK_MEMBER_LIST_ERROR",
  "PRECHECK_LS_REPALY_SCN_ERROR",
  "CHECK_START_STATUS_TRANSFER_TABLETS_ERROR",
  "CHECK_SRC_LS_HAS_ACTIVE_TRANS_ERROR",
  "UPDATE_ALL_TABLET_TO_LS_ERROR",
  "LOCK_TABLET_ON_DEST_LS_FOR_TABLE_LOCK_ERROR",
  "BLOCK_AND_KILL_TX_ERROR",
  "REGISTER_TRANSFER_START_OUT_ERROR",
  "DEST_LS_GET_START_SCN_ERROR",
  "UNBLOCK_TX_ERROR",
  "WAIT_SRC_LS_REPLAY_TO_START_SCN_ERROR",
  "SRC_LS_GET_TABLET_META_ERROR",
  "REGISTER_TRANSFER_START_IN_ERROR",
  "START_TRANS_COMMIT_ERROR",
  "TRANSFER_START_END_ERROR",
  "TRANSFER_FINISH_BEGIN_ERROR",
  "UNLOCK_SRC_AND_DEST_LS_MEMBER_LIST_ERROR",
  "CHECK_LS_LOGICAL_TABLE_REPLACED_ERROR",
  "LOCK_LS_MEMBER_LIST_IN_DOING_ERROR",
  "CHECK_LS_LOGICAL_TABLE_REPLACED_LATER_ERROR",
  "REGISTER_TRANSFER_FINISH_IN_ERROR",
  "WAIT_TRANSFER_TABLET_STATUS_NORMAL_ERROR",
  "WAIT_ALL_LS_REPLICA_REPLAY_FINISH_SCN_ERROR",
  "REGISTER_TRANSFER_OUT_ERROR",
  "UNLOCK_TABLET_FOR_LOCK_ERROR",
  "UNLOCK_LS_MEMBER_LIST_ERROR",
  "FINISH_TRANS_COMMIT_ERROR",
  "TRANSFER_FINISH_END_ERROR",
  "TRANSFER_ABORT_BEGIN_ERROR",
  "UNLOCK_MEMBER_LIST_IN_ABORT_ERROR",
  "ABORT_TRANS_COMMIT_ERROR",
  "TRANSFER_ABORT_END_ERROR",
  "TRANSFER_BACKFILLED_TABLE_BEGIN_ERROR",
  "TX_BACKFILL_ERROR",
  "UNLOCK_MEMBER_LIST_IN_START_ERROR",
  "ON_REGISTER_SUCCESS_ERROR",
  "ON_REPLAY_SUCCESS_ERROR",
  "TRANSFER_REPLACE_BEGIN_ERROR",
  "TRANSFER_REPLACE_END_ERROR",
  "TRANSFER_BACKFILL_START_ERROR",
  "STOP_LS_SCHEDULE_MEMDIUM_ERROR",
};

STATIC_ASSERT(static_cast<int64_t>(ObStorageHADiagModule::MAX_MODULE) == ARRAYSIZEOF(ObStorageDiagModuleStr),
    "ObStorageDiagModuleStr len is mismatch");
STATIC_ASSERT(static_cast<int64_t>(ObStorageHADiagTaskType::MAX_TYPE) == ARRAYSIZEOF(ObStorageDiagTaskTypeStr),
    "ObStorageDiagTaskTypeStr len is mismatch");
STATIC_ASSERT(static_cast<int64_t>(ObStorageHACostItemName::MAX_NAME) == ARRAYSIZEOF(ObStorageHACostItemNameStr),
    "ObStorageHACostItemNameStr len is mismatch");
STATIC_ASSERT(static_cast<int64_t>(ObStorageHACostItemName::MAX_NAME) == ARRAYSIZEOF(ObTransferErrorDiagMsg),
    "ObTransferErrorDiagMsg len is mismatch");

} // namespace share
} // namespace oceanbase
