/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#ifndef OCEANBASE_SHARE_OB_SYNC_STANDBY_DEST_PARSER_H_
#define OCEANBASE_SHARE_OB_SYNC_STANDBY_DEST_PARSER_H_

#include "share/backup/ob_log_restore_struct.h"
#include "share/backup/ob_log_restore_config.h"

namespace oceanbase
{
namespace share
{
const char *const OB_STR_NET_TIMEOUT = "net_timeout";
const char *const OB_STR_HEALTH_CHECK_TIME = "health_check_time";
struct ObSyncStandbyDestStruct final : public ObServiceAttrBase
{
  ObSyncStandbyDestStruct();
  ~ObSyncStandbyDestStruct() {}
  void reset();
  bool is_valid() const;
  int assign(const ObSyncStandbyDestStruct &other);
  // parse standby dest from string generated by gen_standby_dest_str
  int parse_standby_dest_from_str(const ObString &str);
  int gen_standby_dest_str(ObSqlString &str) const;
  virtual int do_parse_key_value(const char *key, const char *value, bool &not_exist) override;
  int set_service_net_timeout(const char *net_timeout, const bool from_inner_table);
  int set_service_health_check_time(const char *health_check_time, const bool from_inner_table);
  int64_t get_service_net_timeout() const { return net_timeout_; }
  int64_t get_service_health_check_time() const { return health_check_time_; }
  TO_STRING_KV(K_(restore_source_service_attr), K_(net_timeout), K_(health_check_time));
  ObRestoreSourceServiceAttr restore_source_service_attr_;
  int64_t net_timeout_;
  int64_t health_check_time_;
  static const int64_t OB_DEFAULT_NET_TIMEOUT = 30_s;
  static const int64_t OB_DEFAULT_HEALTH_CHECK_TIME = 60_s;
private:
  int set_service_time_config_(
      const char *config_value,
      const bool from_inner_table,
      const char *config_name,
      int64_t &target_value);
};

// parse standby dest from string user provided, and generate string for storage
class ObSyncStandbyDestParser : public ObServiceConfigParser
{
public:
  ObSyncStandbyDestParser(ObSyncStandbyDestStruct &sync_standby_dest);
  ~ObSyncStandbyDestParser() {}
  int parse_from(const common::ObString &value, const uint64_t user_tenant_id, const ObCompatibilityMode &compat_mode);
protected:
  virtual int do_parse_token_(char *token, char *value) override;
private:
  int do_parse_net_timeout_(const common::ObString &name, const common::ObString &value);
  int do_parse_health_check_time_(const common::ObString &name, const common::ObString &value);
  int check_sync_standby_dest_connectivity_(const uint64_t user_tenant_id);
private:
  ObSyncStandbyDestStruct &sync_standby_dest_struct_;
  static const int64_t OB_MIN_USER_NET_TIMEOUT;
  static const int64_t OB_MAX_USER_NET_TIMEOUT;
};
}
}
#endif // OCEANBASE_SHARE_OB_SYNC_STANDBY_DEST_PARSER_H_