#!/bin/bash

./test_log_allocator
./test_log_callback_engine
./test_log_index
./test_log_membership_mgr
./test_log_range_info
./test_log_replay_engine_wrapper
./test_log_state_driver_runnable
./test_log_trailer_info
./test_log_type
./test_member_status_checker
./test_ob_log_block
./test_ob_log_cache
./test_ob_log_direct_reader
./test_ob_log_entry
./test_ob_log_entry_header
./test_ob_log_file_pool
./test_ob_log_file_trailer
./test_ob_log_iterator
./test_ob_log_partition_meta_reader
./test_ob_log_reader
./test_ob_log_writer
./test_ob_raw_log_iterator
./test_ob_reader_utility
./test_server_id_map
./test_spmg_fixed_cache
./test_log_state_mgr
./test_log_task
./test_log_reconfirm
