/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_HUNGARIAN_UCA_CI, 72);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SINHALA_UCA_CI, 73);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_GERMAN2_UCA_CI, 74);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_CROATIAN_UCA_CI, 75);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_UNICODE_520_CI, 76);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_VIETNAMESE_CI, 77);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_0900_AI_CI, 78);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DE_PB_0900_AI_CI, 79);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_IS_0900_AI_CI, 80);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LV_0900_AI_CI, 81);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_RO_0900_AI_CI, 82);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SL_0900_AI_CI, 83);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PL_0900_AI_CI, 84);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ET_0900_AI_CI, 85);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_0900_AI_CI, 86);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SV_0900_AI_CI, 87);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_TR_0900_AI_CI, 88);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CS_0900_AI_CI, 89);

} // end common
} // end oceanbase