/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DA_0900_AI_CI, 90);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LT_0900_AI_CI, 91);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SK_0900_AI_CI, 92);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_TRAD_0900_AI_CI, 93);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LA_0900_AI_CI, 94);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_EO_0900_AI_CI, 95);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HU_0900_AI_CI, 96);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HR_0900_AI_CI, 97);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_VI_0900_AI_CI, 98);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_0900_AS_CS, 99);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DE_PB_0900_AS_CS, 100);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_IS_0900_AS_CS, 101);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LV_0900_AS_CS, 102);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_RO_0900_AS_CS, 103);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SL_0900_AS_CS, 104);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PL_0900_AS_CS, 105);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ET_0900_AS_CS, 106);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_0900_AS_CS, 107);

} // end common
} // end oceanbase