/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_POLISH_UCA_CI, 36);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ESTONIAN_UCA_CI, 37);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH_UCA_CI, 38);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SWEDISH_UCA_CI, 39);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_TURKISH_UCA_CI, 40);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CZECH_UCA_CI, 41);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DANISH_UCA_CI, 42);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LITHUANIAN_UCA_CI, 43);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVAK_UCA_CI, 44);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH2_UCA_CI, 45);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMAN_UCA_CI, 46);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PERSIAN_UCA_CI, 47);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ESPERANTO_UCA_CI, 48);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HUNGARIAN_UCA_CI, 49);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SINHALA_UCA_CI, 50);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GERMAN2_UCA_CI, 51);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CROATIAN_UCA_CI, 52);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_UNICODE_520_CI, 53);

} // end common
} // end oceanbase