/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_SJIS_JAPANESE_CI, 42);
DEF_STR_FUNC_INIT(CS_TYPE_SJIS_BIN, 43);
DEF_STR_FUNC_INIT(CS_TYPE_BIG5_CHINESE_CI, 44);
DEF_STR_FUNC_INIT(CS_TYPE_BIG5_BIN, 45);
DEF_STR_FUNC_INIT(CS_TYPE_HKSCS_BIN, 46);
DEF_STR_FUNC_INIT(CS_TYPE_HKSCS31_BIN, 47);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ICELANDIC_UCA_CI, 48);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LATVIAN_UCA_CI, 49);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMANIAN_UCA_CI, 50);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVENIAN_UCA_CI, 51);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_POLISH_UCA_CI, 52);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ESTONIAN_UCA_CI, 53);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH_UCA_CI, 54);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SWEDISH_UCA_CI, 55);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_TURKISH_UCA_CI, 56);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CZECH_UCA_CI, 57);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DANISH_UCA_CI, 58);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LITHUANIAN_UCA_CI, 59);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVAK_UCA_CI, 60);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SPANISH2_UCA_CI, 61);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMAN_UCA_CI, 62);

} // end common
} // end oceanbase