/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_GBK_CHINESE_CI, 0);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GENERAL_CI, 1);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BIN, 2);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_GENERAL_CI, 3);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_BIN, 4);
DEF_STR_FUNC_INIT(CS_TYPE_BINARY, 5);
DEF_STR_FUNC_INIT(CS_TYPE_GBK_BIN, 6);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_UNICODE_CI, 7);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_UNICODE_CI, 8);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_CHINESE_CI, 9);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_BIN, 10);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_SWEDISH_CI, 11);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_BIN, 12);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_BIN, 13);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CI, 14);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CS, 15);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CI, 16);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CS, 17);

} // end common
} // end oceanbase