/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */
namespace oceanbase
{
namespace common
{
extern void __init_str_func0();
extern void __init_str_func1();
extern void __init_str_func2();
extern void __init_str_func3();
extern void __init_str_func4();
extern void __init_str_func5();
extern void __init_str_func6();
extern void __init_str_func7();
extern void __init_str_func8();
extern void __init_str_func9();
extern void __init_str_func10();
extern void __init_str_func11();
extern void __init_str_func12();
extern void __init_str_func13();
extern void __init_str_func14();
extern void __init_str_func15();
extern void __init_str_func16();
extern void __init_str_func17();
extern void __init_str_func18();
extern void __init_str_func19();
extern void __init_str_func20();
extern void __init_str_func21();
extern void __init_str_func22();
extern void __init_str_func23();
extern void __init_str_func24();
extern void __init_str_func25();
extern void __init_str_func26();
extern void __init_str_func27();
extern void __init_str_func28();
extern void __init_str_func29();
extern void __init_str_func30();
extern void __init_str_func31();
extern void __init_str_func32();
extern void __init_str_func33();
extern void __init_str_func34();
extern void __init_str_func35();
extern void __init_str_func36();
extern void __init_str_func37();
extern void __init_str_func38();
extern void __init_str_func39();
extern void __init_str_func40();
extern void __init_str_func41();
extern void __init_str_func42();
extern void __init_str_func43();
extern void __init_str_func44();
extern void __init_str_func45();
extern void __init_str_func46();
extern void __init_str_func47();
extern void __init_str_func48();
extern void __init_str_func49();
extern void __init_str_func50();
extern void __init_str_func51();
extern void __init_str_func52();
extern void __init_str_func53();
extern void __init_str_func54();
extern void __init_str_func55();
extern void __init_str_func56();
extern void __init_str_func57();
extern void __init_str_func58();
extern void __init_str_func59();
extern void __init_str_func60();
extern void __init_str_func61();
extern void __init_str_func62();
extern void __init_str_func63();
extern void __init_str_func64();
extern void __init_str_func65();
extern void __init_str_func66();
extern void __init_str_func67();
extern void __init_str_func68();
extern void __init_str_func69();
extern void __init_str_func70();
extern void __init_str_func71();
extern void __init_str_func72();
extern void __init_str_func73();
extern void __init_str_func74();
extern void __init_str_func75();
extern void __init_str_func76();
extern void __init_str_func77();
extern void __init_str_func78();
extern void __init_str_func79();
extern void __init_str_func80();
extern void __init_str_func81();
extern void __init_str_func82();
extern void __init_str_func83();
extern void __init_str_func84();
extern void __init_str_func85();
extern void __init_str_func86();
extern void __init_str_func87();
extern void __init_str_func88();
extern void __init_str_func89();
extern void __init_str_func90();
extern void __init_str_func91();
extern void __init_str_func92();
extern void __init_str_func93();
extern void __init_str_func94();
extern void __init_str_func95();
extern void __init_str_func96();
extern void __init_str_func97();
extern void __init_str_func98();
extern void __init_str_func99();
extern void __init_str_func100();
extern void __init_str_func101();
extern void __init_str_func102();
extern void __init_str_func103();
extern void __init_str_func104();
extern void __init_str_func105();
extern void __init_str_func106();
extern void __init_str_func107();
extern void __init_str_func108();
extern void __init_str_func109();
extern void __init_str_func110();
extern void __init_str_func111();
extern void __init_str_func112();
extern void __init_str_func113();
extern void __init_str_func114();
extern void __init_str_func115();
extern void __init_str_func116();
extern void __init_str_func117();
extern void __init_str_func118();
extern void __init_str_func119();
extern void __init_str_func120();
extern void __init_str_func121();
extern void __init_str_func122();
extern void __init_str_func123();
extern void __init_str_func124();
extern void __init_str_func125();
extern void __init_str_func126();
extern void __init_str_func127();
extern void __init_str_func128();
extern void __init_str_func129();
extern void __init_str_func130();
extern void __init_str_func131();
extern void __init_str_func132();
extern void __init_str_func133();
extern void __init_str_func134();
extern void __init_str_func135();
extern void __init_str_func136();
extern void __init_str_func137();
extern void __init_str_func138();
extern void __init_str_func139();
extern void __init_str_func140();
extern void __init_str_func141();
extern void __init_str_func142();
extern void __init_str_func143();
extern void __init_str_func144();
extern void __init_str_func145();
extern void __init_str_func146();
extern void __init_str_func147();
extern void __init_str_func148();
extern void __init_str_func149();
extern void __init_str_func150();
extern void __init_str_func151();
extern void __init_str_func152();
extern void __init_str_func153();
extern void __init_str_func154();
extern void __init_str_func155();
extern void __init_str_func156();
extern void __init_str_func157();
extern void __init_str_func158();
extern void __init_str_func159();
extern void __init_str_func160();
extern void __init_str_func161();
extern void __init_str_func162();
extern void __init_str_func163();
extern void __init_str_func164();
extern void __init_str_func165();
extern void __init_str_func166();
void __init_all_str_funcs() {
  __init_str_func0();
  __init_str_func1();
  __init_str_func2();
  __init_str_func3();
  __init_str_func4();
  __init_str_func5();
  __init_str_func6();
  __init_str_func7();
  __init_str_func8();
  __init_str_func9();
  __init_str_func10();
  __init_str_func11();
  __init_str_func12();
  __init_str_func13();
  __init_str_func14();
  __init_str_func15();
  __init_str_func16();
  __init_str_func17();
  __init_str_func18();
  __init_str_func19();
  __init_str_func20();
  __init_str_func21();
  __init_str_func22();
  __init_str_func23();
  __init_str_func24();
  __init_str_func25();
  __init_str_func26();
  __init_str_func27();
  __init_str_func28();
  __init_str_func29();
  __init_str_func30();
  __init_str_func31();
  __init_str_func32();
  __init_str_func33();
  __init_str_func34();
  __init_str_func35();
  __init_str_func36();
  __init_str_func37();
  __init_str_func38();
  __init_str_func39();
  __init_str_func40();
  __init_str_func41();
  __init_str_func42();
  __init_str_func43();
  __init_str_func44();
  __init_str_func45();
  __init_str_func46();
  __init_str_func47();
  __init_str_func48();
  __init_str_func49();
  __init_str_func50();
  __init_str_func51();
  __init_str_func52();
  __init_str_func53();
  __init_str_func54();
  __init_str_func55();
  __init_str_func56();
  __init_str_func57();
  __init_str_func58();
  __init_str_func59();
  __init_str_func60();
  __init_str_func61();
  __init_str_func62();
  __init_str_func63();
  __init_str_func64();
  __init_str_func65();
  __init_str_func66();
  __init_str_func67();
  __init_str_func68();
  __init_str_func69();
  __init_str_func70();
  __init_str_func71();
  __init_str_func72();
  __init_str_func73();
  __init_str_func74();
  __init_str_func75();
  __init_str_func76();
  __init_str_func77();
  __init_str_func78();
  __init_str_func79();
  __init_str_func80();
  __init_str_func81();
  __init_str_func82();
  __init_str_func83();
  __init_str_func84();
  __init_str_func85();
  __init_str_func86();
  __init_str_func87();
  __init_str_func88();
  __init_str_func89();
  __init_str_func90();
  __init_str_func91();
  __init_str_func92();
  __init_str_func93();
  __init_str_func94();
  __init_str_func95();
  __init_str_func96();
  __init_str_func97();
  __init_str_func98();
  __init_str_func99();
  __init_str_func100();
  __init_str_func101();
  __init_str_func102();
  __init_str_func103();
  __init_str_func104();
  __init_str_func105();
  __init_str_func106();
  __init_str_func107();
  __init_str_func108();
  __init_str_func109();
  __init_str_func110();
  __init_str_func111();
  __init_str_func112();
  __init_str_func113();
  __init_str_func114();
  __init_str_func115();
  __init_str_func116();
  __init_str_func117();
  __init_str_func118();
  __init_str_func119();
  __init_str_func120();
  __init_str_func121();
  __init_str_func122();
  __init_str_func123();
  __init_str_func124();
  __init_str_func125();
  __init_str_func126();
  __init_str_func127();
  __init_str_func128();
  __init_str_func129();
  __init_str_func130();
  __init_str_func131();
  __init_str_func132();
  __init_str_func133();
  __init_str_func134();
  __init_str_func135();
  __init_str_func136();
  __init_str_func137();
  __init_str_func138();
  __init_str_func139();
  __init_str_func140();
  __init_str_func141();
  __init_str_func142();
  __init_str_func143();
  __init_str_func144();
  __init_str_func145();
  __init_str_func146();
  __init_str_func147();
  __init_str_func148();
  __init_str_func149();
  __init_str_func150();
  __init_str_func151();
  __init_str_func152();
  __init_str_func153();
  __init_str_func154();
  __init_str_func155();
  __init_str_func156();
  __init_str_func157();
  __init_str_func158();
  __init_str_func159();
  __init_str_func160();
  __init_str_func161();
  __init_str_func162();
  __init_str_func163();
  __init_str_func164();
  __init_str_func165();
  __init_str_func166();
}
} // end common
} // end oceanbase