/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_VIETNAMESE_CI, 54);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_ICELANDIC_UCA_CI, 55);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_LATVIAN_UCA_CI, 56);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_ROMANIAN_UCA_CI, 57);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SLOVENIAN_UCA_CI, 58);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_POLISH_UCA_CI, 59);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_ESTONIAN_UCA_CI, 60);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SPANISH_UCA_CI, 61);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SWEDISH_UCA_CI, 62);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_TURKISH_UCA_CI, 63);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_CZECH_UCA_CI, 64);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_DANISH_UCA_CI, 65);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_LITHUANIAN_UCA_CI, 66);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SLOVAK_UCA_CI, 67);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_SPANISH2_UCA_CI, 68);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_ROMAN_UCA_CI, 69);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_PERSIAN_UCA_CI, 70);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16_ESPERANTO_UCA_CI, 71);

} // end common
} // end oceanbase