/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_DANISH_CI, 21);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_GERMAN2_CI, 22);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_BIN, 23);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_GENERAL_CI, 24);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_GENERAL_CS, 25);
DEF_STR_FUNC_INIT(CS_TYPE_LATIN1_SPANISH_CI, 26);
DEF_STR_FUNC_INIT(CS_TYPE_GB2312_CHINESE_CI, 27);
DEF_STR_FUNC_INIT(CS_TYPE_GB2312_BIN, 28);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_BIN, 29);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CI, 30);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CS, 31);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CI, 32);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CS, 33);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CI, 34);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CS, 35);
DEF_STR_FUNC_INIT(CS_TYPE_ASCII_GENERAL_CI, 36);
DEF_STR_FUNC_INIT(CS_TYPE_ASCII_BIN, 37);
DEF_STR_FUNC_INIT(CS_TYPE_TIS620_THAI_CI, 38);
DEF_STR_FUNC_INIT(CS_TYPE_TIS620_BIN, 39);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16LE_GENERAL_CI, 40);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16LE_BIN, 41);

} // end common
} // end oceanbase