/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AI_CI, 147);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AS_CS, 148);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AI_CI, 149);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AS_CS, 150);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AI_CI, 151);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AS_CS, 152);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AI_CI, 153);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AS_CS, 154);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AI_CI, 155);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AS_CS, 156);
DEF_STR_FUNC_INIT(CS_TYPE_DEC8_SWEDISH_CI, 157);
DEF_STR_FUNC_INIT(CS_TYPE_DEC8_BIN, 158);
DEF_STR_FUNC_INIT(CS_TYPE_CP850_GENERAL_CI, 159);
DEF_STR_FUNC_INIT(CS_TYPE_CP850_BIN, 160);
DEF_STR_FUNC_INIT(CS_TYPE_HP8_ENGLISH_CI, 161);
DEF_STR_FUNC_INIT(CS_TYPE_HP8_BIN, 162);
DEF_STR_FUNC_INIT(CS_TYPE_MACROMAN_GENERAL_CI, 163);
DEF_STR_FUNC_INIT(CS_TYPE_MACROMAN_BIN, 164);
DEF_STR_FUNC_INIT(CS_TYPE_SWE7_SWEDISH_CI, 165);
DEF_STR_FUNC_INIT(CS_TYPE_SWE7_BIN, 166);
DEF_STR_FUNC_INIT(CS_TYPE_MAX, 167);

} // end common
} // end oceanbase