/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_str_datum_funcs_compilation.ipp"

namespace oceanbase
{
namespace common
{
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CI, 18);
DEF_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CS, 19);
DEF_STR_FUNC_INIT(CS_TYPE_ASCII_GENERAL_CI, 20);
DEF_STR_FUNC_INIT(CS_TYPE_ASCII_BIN, 21);
DEF_STR_FUNC_INIT(CS_TYPE_TIS620_THAI_CI, 22);
DEF_STR_FUNC_INIT(CS_TYPE_TIS620_BIN, 23);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16LE_GENERAL_CI, 24);
DEF_STR_FUNC_INIT(CS_TYPE_UTF16LE_BIN, 25);
DEF_STR_FUNC_INIT(CS_TYPE_SJIS_JAPANESE_CI, 26);
DEF_STR_FUNC_INIT(CS_TYPE_SJIS_BIN, 27);
DEF_STR_FUNC_INIT(CS_TYPE_BIG5_CHINESE_CI, 28);
DEF_STR_FUNC_INIT(CS_TYPE_BIG5_BIN, 29);
DEF_STR_FUNC_INIT(CS_TYPE_HKSCS_BIN, 30);
DEF_STR_FUNC_INIT(CS_TYPE_HKSCS31_BIN, 31);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ICELANDIC_UCA_CI, 32);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LATVIAN_UCA_CI, 33);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ROMANIAN_UCA_CI, 34);
DEF_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SLOVENIAN_UCA_CI, 35);

} // end common
} // end oceanbase