#package_name:dbms_upgrade
#author: linlin.xll

CREATE OR REPLACE PACKAGE BODY "__DBMS_UPGRADE" IS
  PROCEDURE UPGRADE(package_name VARCHAR2);
    PRAGMA INTERFACE(c, UPGRADE_SINGLE);
  PROCEDURE UPGRADE_ALL;
    PRAGMA INTERFACE(c, UPGRADE_ALL);
END;
//
