CREATE OR REPLACE PACKAGE BODY DBMS_SESSION
  PROCEDURE SET_IDENTIFIER(CLIENT_ID VARCHAR(65535));
  PRAGMA INTERFACE(c, SET_IDENTIFIER);
  PROCEDURE CLEAR_IDENTIFIER();
  PRAGMA INTERFACE(c, CLEAR_IDENTIFIER);
END;
//
