#package_name:DBMS_XMLDOM
#author:zongmei.zzm

CREATE OR REPLACE TYPE BODY DOMDocument AS
  CONSTRUCTOR FUNCTION DOMDocument RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMNode AS
  CONSTRUCTOR FUNCTION DOMNode RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR_NOOP);
END;
//

CREATE OR REPLACE TYPE BODY DOMNodeList AS
  CONSTRUCTOR FUNCTION DOMNodeList RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR_NOOP);
END;
//

CREATE OR REPLACE PACKAGE BODY dbms_xmldom AS
  PROCEDURE freeDocument(doc IN DOMDocument);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_FREEDOCUMENT);

  FUNCTION getChildNodes(n IN DOMNode) RETURN DOMNodeList;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETCHILDNODES);

  FUNCTION getFirstChild(n IN DOMNode) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETFIRSTCHILD);

  FUNCTION getElementsByTagName(doc IN DOMDocument, name IN VARCHAR2) RETURN DOMNodeList;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETELEMENTSBYTAGNAME);

  FUNCTION getLength(nl IN DOMNodeList) RETURN NUMBER;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETLENGTH);

  FUNCTION getNodeValue(n IN DOMNode) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETNODEVALUE);

  FUNCTION item(nl IN DOMNodeList, idx IN NUMBER) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ITEM);
END dbms_xmldom;
//
