#package_name: dbms_trusted_certificate_manager
#author: tony.wzh

CREATE OR REPLACE PACKAGE BODY dbms_trusted_certificate_manager

  PROCEDURE ADD_TRUSTED_CERTIFICATE(
    COMMON_NAME VARCHAR(256),
    DESCRIPTION VARCHAR(256),
    CONTENT     LONGTEXT);
  PRAGMA INTERFACE(C, ADD_TRUSTED_CERTIFICATE);

  PROCEDURE DELETE_TRUSTED_CERTIFICATE(
    COMMON_NAME VARCHAR(256));
  PRAGMA INTERFACE(C, DELETE_TRUSTED_CERTIFICATE);

  PROCEDURE UPDATE_TRUSTED_CERTIFICATE(
    COMMON_NAME  VARCHAR(256),
    DESCRIPTION  VARCHAR(256),
    CONTENT      LONGTEXT);
  PRAGMA INTERFACE(C, UPDATE_TRUSTED_CERTIFICATE);

END dbms_trusted_certificate_manager;