#package_name:DBMS_XMLPARSER
#author:zongmei.zzm

CREATE OR REPLACE TYPE BODY Parser AS
  CONSTRUCTOR FUNCTION Parser RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE PACKAGE BODY dbms_xmlparser AS
  FUNCTION newParser RETURN Parser;
  PRAGMA INTERFACE(c, DBMS_XMLPARSER_NEWPARSER);

  PROCEDURE parseClob(p IN Parser, doc IN CLOB);
  PRAGMA INTERFACE(c, DBMS_XMLPARSER_PARSECLOB);

  FUNCTION getDocument(p IN Parser) RETURN DBMS_XMLDOM.DOMDocument;
  PRAGMA INTERFACE(c, DBMS_XMLPARSER_GETDOCUMENT);

  PROCEDURE freeParser(p IN Parser);
  PRAGMA INTERFACE(c, DBMS_XMLPARSER_FREEPARSER);
END dbms_xmlparser;
//
