#package_name:DBMS_XMLDOM
#author:zongmei.zzm

CREATE OR REPLACE TYPE DOMDocument FORCE OID '300036' AS OPAQUE
(
  CONSTRUCTOR FUNCTION DOMDocument RETURN SELF AS RESULT
);
//

CREATE OR REPLACE TYPE DOMNode FORCE OID '300037' AS OPAQUE
(
  CONSTRUCTOR FUNCTION DOMNode RETURN SELF AS RESULT
);
//

CREATE OR REPLACE TYPE DOMNodeList FORCE OID '300038' AS OPAQUE
(
  CONSTRUCTOR FUNCTION DOMNodeList RETURN SELF AS RESULT
);
//

CREATE OR REPLACE PACKAGE dbms_xmldom AUTHID CURRENT_USER AS
  SUBTYPE DOMDocument IS SYS.DOMDocument;
  SUBTYPE DOMNode     IS SYS.DOMNode;
  SUBTYPE DOMNodeList IS SYS.DOMNodeList;

  ELEMENT_NODE       CONSTANT PLS_INTEGER := 1;
  ATTRIBUTE_NODE     CONSTANT PLS_INTEGER := 2;
  TEXT_NODE          CONSTANT PLS_INTEGER := 3;
  CDATA_SECTION_NODE CONSTANT PLS_INTEGER := 4;
  COMMENT_NODE       CONSTANT PLS_INTEGER := 8;
  DOCUMENT_NODE      CONSTANT PLS_INTEGER := 9;

  PROCEDURE freeDocument(doc IN DOMDocument);
  FUNCTION getChildNodes(n IN DOMNode) RETURN DOMNodeList;
  FUNCTION getElementsByTagName(doc IN DOMDocument, name IN VARCHAR2) RETURN DOMNodeList;
  FUNCTION getLength(nl IN DOMNodeList) RETURN NUMBER;
  FUNCTION getNodeValue(n IN DOMNode) RETURN VARCHAR2;
  FUNCTION item(nl IN DOMNodeList, idx IN NUMBER) RETURN DOMNode;
END dbms_xmldom;
//
