#package_name:DBMS_XMLDOM
#author:zongmei.zzm

CREATE OR REPLACE TYPE BODY DOMDocument AS
  CONSTRUCTOR FUNCTION DOMDocument RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMNode AS
  CONSTRUCTOR FUNCTION DOMNode RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMNodeList AS
  CONSTRUCTOR FUNCTION DOMNodeList RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMAttr AS
  CONSTRUCTOR FUNCTION DOMAttr RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMCharacterData AS
  CONSTRUCTOR FUNCTION DOMCharacterData RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMElement AS
  CONSTRUCTOR FUNCTION DOMElement RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE TYPE BODY DOMText AS
  CONSTRUCTOR FUNCTION DOMText RETURN SELF AS RESULT;
  PRAGMA INTERFACE(c, XML_OPAQUE_CONSTRUCTOR);
END;
//

CREATE OR REPLACE PACKAGE BODY dbms_xmldom AS
  PROCEDURE freeDocument(doc IN DOMDocument);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_FREEDOCUMENT);

  FUNCTION getChildNodes(n IN DOMNode) RETURN DOMNodeList;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETCHILDNODES);

  FUNCTION getFirstChild(n IN DOMNode) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETFIRSTCHILD);

  FUNCTION getElementsByTagName(doc IN DOMDocument, name IN VARCHAR2) RETURN DOMNodeList;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETELEMENTSBYTAGNAME);

  FUNCTION getLength(nl IN DOMNodeList) RETURN NUMBER;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETLENGTH);

  FUNCTION getNodeValue(n IN DOMNode) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETNODEVALUE);

  FUNCTION item(nl IN DOMNodeList, idx IN NUMBER) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ITEM);

  -- Node manipulation
  FUNCTION appendChild(n IN DOMNode, newChild IN DOMNode) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_APPENDCHILD);

  FUNCTION createElement(doc IN DOMDocument, tagName IN VARCHAR2) RETURN DOMElement;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_CREATEELEMENT);

  FUNCTION createElement(doc IN DOMDocument, tagName IN VARCHAR2, ns IN VARCHAR2) RETURN DOMElement;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_CREATEELEMENT);

  FUNCTION createTextNode(doc IN DOMDocument, data IN VARCHAR2) RETURN DOMText;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_CREATETEXTNODE);

  FUNCTION makeCharacterData(n IN DOMNode) RETURN DOMCharacterData;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKECHARACTERDATA);

  FUNCTION makeNode(doc IN DOMDocument) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION makeNode(n IN DOMNode) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION makeNode(attr IN DOMAttr) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION makeNode(cd IN DOMCharacterData) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION makeNode(elem IN DOMElement) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION makeNode(t IN DOMText) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_MAKENODE);

  FUNCTION removeChild(n IN DOMNode, oldChild IN DOMNode) RETURN DOMNode;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_REMOVECHILD);

  PROCEDURE setAttribute(elem IN DOMElement, name IN VARCHAR2, newvalue IN VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_SETATTRIBUTE);

  PROCEDURE setAttribute(elem IN DOMElement, name IN VARCHAR2, newvalue IN VARCHAR2, ns IN VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_SETATTRIBUTE);

  -- Node query / inspection
  FUNCTION getData(cd IN DOMCharacterData) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETDATA);

  FUNCTION getDocumentElement(doc IN DOMDocument) RETURN DOMElement;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETDOCUMENTELEMENT);

  FUNCTION getLocalName(attr IN DOMAttr) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETLOCALNAME);

  FUNCTION getLocalName(elem IN DOMElement) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETLOCALNAME);

  FUNCTION getNodeName(n IN DOMNode) RETURN VARCHAR2;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETNODENAME);

  FUNCTION getNodeType(n IN DOMNode) RETURN NUMBER;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETNODETYPE);

  FUNCTION getXmlType(doc IN DOMDocument) RETURN XMLTYPE;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_GETXMLTYPE);

  -- Handle emptiness check
  FUNCTION isNull(n IN DOMNode) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(d IN DOMDocument) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(nl IN DOMNodeList) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(attr IN DOMAttr) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(cd IN DOMCharacterData) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(elem IN DOMElement) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  FUNCTION isNull(t IN DOMText) RETURN BOOLEAN;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_ISNULL);

  -- Document operations
  FUNCTION newDOMDocument RETURN DOMDocument;
  PRAGMA INTERFACE(c, DBMS_XMLDOM_NEWDOMDOCUMENT);

  PROCEDURE setCharset(doc IN DOMDocument, charset IN VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_SETCHARSET);

  PROCEDURE setVersion(doc IN DOMDocument, version IN VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_SETVERSION);

  PROCEDURE writeToBuffer(doc IN DOMDocument, buffer IN OUT VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_WRITETOBUFFER);

  PROCEDURE writeToBuffer(n IN DOMNode, buffer IN OUT VARCHAR2);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_WRITETOBUFFER);

  PROCEDURE writeToClob(doc IN DOMDocument, cl IN OUT CLOB);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_WRITETOCLOB);

  PROCEDURE writeToClob(n IN DOMNode, cl IN OUT CLOB);
  PRAGMA INTERFACE(c, DBMS_XMLDOM_WRITETOCLOB);
END dbms_xmldom;
//
