#package_name:dbms_application_info
#author: guoyun.lgy
CREATE OR REPLACE PACKAGE BODY DBMS_APPLICATION_INFO
  PROCEDURE READ_CLIENT_INFO(OUT CLIENT_INFO VARCHAR(65535));
  PRAGMA INTERFACE(c, READ_CLIENT_INFO);
  PROCEDURE READ_MODULE(OUT MODULE_NAME VARCHAR(65535), OUT ACTION_NAME VARCHAR(65535));
  PRAGMA INTERFACE(c, READ_MODULE);
  PROCEDURE SET_ACTION(IN ACTION_NAME VARCHAR(65535));
  PRAGMA INTERFACE(c, SET_ACTION);
  PROCEDURE SET_CLIENT_INFO(IN CLIENT_INFO VARCHAR(65535));
  PRAGMA INTERFACE(c, SET_CLIENT_INFO);
  PROCEDURE SET_MODULE(IN MODULE_NAME VARCHAR(65535), IN ACTION_NAME VARCHAR(65535));
  PRAGMA INTERFACE(c, SET_MODULE);
END;


//

