#package_name:DBMS_LOB_MANAGER
#author: wuhuang.wh

CREATE OR REPLACE PACKAGE BODY "DBMS_LOB_MANAGER" IS

  PROCEDURE CHECK_LOB(
    table_ids         IN VARCHAR2 := NULL
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CHECK_LOB);

  PROCEDURE CANCEL_JOB(
    task_type         IN VARCHAR2
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CANCEL_JOB);

  PROCEDURE SUSPEND_JOB(
    task_type         IN VARCHAR2
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_SUSPEND_JOB);

  PROCEDURE RESUME_JOB(
    task_type         IN VARCHAR2
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_RESUME_JOB);

  PROCEDURE REPAIR_LOB(
    table_id          IN NUMBER DEFAULT NULL,
    tablet_ids        IN VARCHAR2 DEFAULT NULL
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_REPAIR_LOB);

  PROCEDURE CHECK_LOB_INNER;
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CHECK_LOB_INNER);

  PROCEDURE RESCHEDULE_JOB(
    start_date        IN TIMESTAMP WITH TIME ZONE,
    repeat_interval   IN VARCHAR2
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_RESCHEDULE_JOB);

END;
//