#package_name:DBMS_LOB_MANAGER
#author: wuhuang.wh

CREATE OR REPLACE PACKAGE BODY DBMS_LOB_MANAGER

  PROCEDURE CHECK_LOB(
    IN table_ids         JSON DEFAULT NULL
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CHECK_LOB);

  PROCEDURE CANCEL_JOB(
    IN task_type         VARCHAR(65535)
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CANCEL_JOB);

  PROCEDURE SUSPEND_JOB(
    IN task_type         VARCHAR(65535)
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_SUSPEND_JOB);

  PROCEDURE RESUME_JOB(
    IN task_type         VARCHAR(65535)
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_RESUME_JOB);

  PROCEDURE REPAIR_LOB(
    IN table_id          BIGINT DEFAULT NULL,
    IN tablet_ids        JSON   DEFAULT NULL
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_REPAIR_LOB);

  PROCEDURE CHECK_LOB_INNER();
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_CHECK_LOB_INNER);

  PROCEDURE RESCHEDULE_JOB(
    IN start_date        TIMESTAMP(6),
    IN repeat_interval   VARCHAR(65535)
  );
  PRAGMA INTERFACE(C, DBMS_LOB_MANAGER_RESCHEDULE_JOB);

END;
//