#package_name: dbms_schema
#author: zhaoziqian.zzq

CREATE OR REPLACE PACKAGE BODY DBMS_SCHEMA IS
  PROCEDURE RECYCLE_SCHEMA_HISTORY;
  PRAGMA INTERFACE(C, DBMS_SCHEMA_RECYCLE_SCHEMA_HISTORY);

  PROCEDURE RUN_INSPECTION;
  PRAGMA INTERFACE(C, DBMS_SCHEMA_RUN_INSPECTION);
END;
//
