#package_name: DBMS_DDL
#author: haohao.hao

CREATE OR REPLACE PACKAGE DBMS_DDL AUTHID CURRENT_USER AS
  MALFORMED_WRAP_INPUT EXCEPTION;
  PRAGMA EXCEPTION_INIT(MALFORMED_WRAP_INPUT, -9806);

  FUNCTION WRAP(DDL VARCHAR2) RETURN VARCHAR2;
  FUNCTION WRAP(DDL DBMS_SQL.VARCHAR2S, LB PLS_INTEGER, UB PLS_INTEGER) RETURN DBMS_SQL.VARCHAR2S;
  FUNCTION WRAP(DDL DBMS_SQL.VARCHAR2A, LB PLS_INTEGER, UB PLS_INTEGER) RETURN DBMS_SQL.VARCHAR2A;

  PROCEDURE CREATE_WRAPPED(DDL VARCHAR2);
  PROCEDURE CREATE_WRAPPED(DDL DBMS_SQL.VARCHAR2S, LB PLS_INTEGER, UB PLS_INTEGER);
  PROCEDURE CREATE_WRAPPED(DDL DBMS_SQL.VARCHAR2A, LB PLS_INTEGER, UB PLS_INTEGER);
END DBMS_DDL;
//
