#package_name:dbms_ai_service
#author:shenyunlong.syl

CREATE OR REPLACE PACKAGE BODY dbms_ai_service
  PROCEDURE create_ai_model(IN name VARCHAR(128), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_CREATE_AI_MODEL_MYSQL);

  PROCEDURE drop_ai_model(IN name VARCHAR(128));
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_DROP_AI_MODEL_MYSQL);

  PROCEDURE create_ai_model_endpoint(IN name VARCHAR(128), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_CREATE_AI_MODEL_ENDPOINT_MYSQL);

  PROCEDURE alter_ai_model_endpoint(IN name VARCHAR(128), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_ALTER_AI_MODEL_ENDPOINT_MYSQL);

  PROCEDURE drop_ai_model_endpoint(IN name VARCHAR(128));
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_DROP_AI_MODEL_ENDPOINT_MYSQL);

  PROCEDURE register_provider(IN name VARCHAR(256), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_REGISTER_PROVIDER_MYSQL);

  PROCEDURE unregister_provider(IN name VARCHAR(256));
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_UNREGISTER_PROVIDER_MYSQL);

  PROCEDURE alter_provider(IN name VARCHAR(256), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_ALTER_PROVIDER_MYSQL);

  PROCEDURE create_ai_gateway(IN name VARCHAR(256), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_CREATE_AI_GATEWAY_MYSQL);

  PROCEDURE alter_ai_gateway(IN name VARCHAR(256), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_ALTER_AI_GATEWAY_MYSQL);

  PROCEDURE drop_ai_gateway(IN name VARCHAR(256));
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_DROP_AI_GATEWAY_MYSQL);

  PROCEDURE alter_model_profile(IN model VARCHAR(256), IN params JSON);
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_ALTER_MODEL_PROFILE_MYSQL);

  PROCEDURE drop_model_profile(IN model VARCHAR(256));
    PRAGMA INTERFACE(C, DBMS_AI_SERVICE_DROP_MODEL_PROFILE_MYSQL);
END dbms_ai_service;
