#package_name: DBMS_DAILY_MAINTENANCE
#author: ouyanghongrong.oyhr

CREATE OR REPLACE PACKAGE BODY dbms_daily_maintenance IS

  PROCEDURE TRIGGER_WINDOW_COMPACTION_PROC (
    is_daily_maintenance IN BOOLEAN DEFAULT FALSE
  );
  PRAGMA INTERFACE(C, DBMS_DAILY_MAINTENANCE_TRIGGER_WINDOW_COMPACTION);

  PROCEDURE SET_THREAD_COUNT (
    thread_count IN INT
  );
  PRAGMA INTERFACE(C, DBMS_DAILY_MAINTENANCE_SET_THREAD_COUNT);

END dbms_daily_maintenance;
//