#type_name:sdo_util
#package_name:sdo_util

CREATE OR REPLACE PACKAGE BODY SDO_UTIL IS

  -- Extract vertices from SDO_GEOMETRY
  FUNCTION GETVERTICES(geom IN SDO_GEOMETRY) RETURN VERTEX_SET_TYPE;
  PRAGMA INTERFACE(c, SDO_UTIL_GETVERTICES);

END SDO_UTIL;
//
