#type_name:sdo_util
#package_name:sdo_util

-- Define VERTEX_TYPE for SDO_UTIL.GETVERTICES function
CREATE OR REPLACE TYPE VERTEX_TYPE FORCE OID '300033' IS OBJECT (
 X NUMBER,
 Y NUMBER,
 Z NUMBER,
 W NUMBER,
 V1 NUMBER,
 V2 NUMBER,
 V3 NUMBER,
 V4 NUMBER,
 V5 NUMBER,
 V6 NUMBER,
 V7 NUMBER,
 V8 NUMBER,
 V9 NUMBER,
 V10 NUMBER,
 V11 NUMBER,
 ID NUMBER
);
//

CREATE OR REPLACE TYPE VERTEX_SET_TYPE FORCE OID '300034' AS TABLE OF VERTEX_TYPE;
//

CREATE OR REPLACE PACKAGE SDO_UTIL IS
  FUNCTION GETVERTICES(geom IN SDO_GEOMETRY) RETURN VERTEX_SET_TYPE;
END SDO_UTIL;
//
