/**
 * Copyright (c) 2023 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

FUNCTION_TYPE(MVIEW_JOB) //物化视图
FUNCTION_TYPE(STAT_MAINTENANCE_JOB, SHADOW) //统计信息
FUNCTION_TYPE(OLAP_ASYNC_JOB) //olap异步任务
FUNCTION_TYPE(MYSQL_EVENT_JOB) //mysql_event
FUNCTION_TYPE(NODE_BALANCE_JOB, SHADOW) //负载均衡
FUNCTION_TYPE(EXT_FILE_REFRESH_JOB, SHADOW) //外表刷新
FUNCTION_TYPE(VECTOR_INDEX_REFRESH_JOB, SHADOW) //向量索引刷新
FUNCTION_TYPE(DATA_DICT_DUMP_JOB, SHADOW) //数据字典dump
FUNCTION_TYPE(FLUSH_NCOMP_DLL_JOB, SHADOW) //刷新ncomp_dll
FUNCTION_TYPE(POLLING_ASK_JOB_FOR_PL_RECOMPILE, SHADOW) //轮询检查是否需要开启pl重编译任务
FUNCTION_TYPE(DYNAMIC_PARTITION_MANAGE_JOB, SHADOW) //定时动态分区管理
FUNCTION_TYPE(DAILY_MAINTENANCE_JOB, SHADOW) //定时窗口合并任务