

// [0, 100) for inner group
//CGID_DEF(group_name, group_id, worker_concurrency)
CGID_DEF(OBCG_DEFAULT, 0)
CGID_DEF(OBCG_CLOG, 1)
CGID_DEF(OBCG_ELECTION, 2)
CGID_DEF(OBCG_ID_SERVICE, 5)
CGID_DEF(OBCG_ID_SQL_REQ_LEVEL1, 6, 4)
CGID_DEF(OBCG_ID_SQL_REQ_LEVEL2, 7, 4)
CGID_DEF(OBCG_ID_SQL_REQ_LEVEL3, 8, 4)
CGID_DEF(OBCG_DETECT_RS, 9)
CGID_DEF(OBCG_LOC_CACHE, 10)
CGID_DEF(OBCG_SQL_NIO, 11)
CGID_DEF(OBCG_MYSQL_LOGIN, 12)
CGID_DEF(OBCG_LQ, 100)
