/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SPANISH2_UCA_CI, 84);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_ROMAN_UCA_CI, 85);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_PERSIAN_UCA_CI, 86);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_ESPERANTO_UCA_CI, 87);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_HUNGARIAN_UCA_CI, 88);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SINHALA_UCA_CI, 89);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_GERMAN2_UCA_CI, 90);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_CROATIAN_UCA_CI, 91);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_UNICODE_520_CI, 92);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_VIETNAMESE_CI, 93);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_0900_AI_CI, 94);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DE_PB_0900_AI_CI, 95);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_IS_0900_AI_CI, 96);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LV_0900_AI_CI, 97);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_RO_0900_AI_CI, 98);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SL_0900_AI_CI, 99);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PL_0900_AI_CI, 100);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ET_0900_AI_CI, 101);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_0900_AI_CI, 102);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SV_0900_AI_CI, 103);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_TR_0900_AI_CI, 104);

} // end sql
} // end oceanbase