/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_BIN, 19);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CI, 20);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_PINYIN_CS, 21);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CI, 22);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_RADICAL_CS, 23);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CI, 24);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_2022_STROKE_CS, 25);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_ASCII_GENERAL_CI, 26);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_ASCII_BIN, 27);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_TIS620_THAI_CI, 28);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_TIS620_BIN, 29);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16LE_GENERAL_CI, 30);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16LE_BIN, 31);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SJIS_JAPANESE_CI, 32);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_SJIS_BIN, 33);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_BIG5_CHINESE_CI, 34);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_BIG5_BIN, 35);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HKSCS_BIN, 36);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_HKSCS31_BIN, 37);

} // end sql
} // end oceanbase