/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_0900_BIN, 126);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_NB_0900_AI_CI, 127);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_NB_0900_AS_CS, 128);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_NN_0900_AI_CI, 129);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_NN_0900_AS_CS, 130);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AI_CI, 131);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SR_LATN_0900_AS_CS, 132);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AI_CI, 133);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BS_0900_AS_CS, 134);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AI_CI, 135);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BG_0900_AS_CS, 136);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AI_CI, 137);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GL_0900_AS_CS, 138);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AI_CI, 139);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_MN_CYRL_0900_AS_CS, 140);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_DEC8_SWEDISH_CI, 141);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_DEC8_BIN, 142);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_MAX, 143);

} // end sql
} // end oceanbase