/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CS_0900_AI_CI, 95);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DA_0900_AI_CI, 96);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LT_0900_AI_CI, 97);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SK_0900_AI_CI, 98);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_TRAD_0900_AI_CI, 99);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LA_0900_AI_CI, 100);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_EO_0900_AI_CI, 101);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HU_0900_AI_CI, 102);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HR_0900_AI_CI, 103);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_VI_0900_AI_CI, 104);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_0900_AS_CS, 105);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_DE_PB_0900_AS_CS, 106);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_IS_0900_AS_CS, 107);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_LV_0900_AS_CS, 108);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_RO_0900_AS_CS, 109);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SL_0900_AS_CS, 110);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PL_0900_AS_CS, 111);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ET_0900_AS_CS, 112);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ES_0900_AS_CS, 113);

} // end sql
} // end oceanbase