/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GBK_CHINESE_CI, 0);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GENERAL_CI, 1);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_BIN, 2);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_GENERAL_CI, 3);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_BIN, 4);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_BINARY, 5);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GBK_BIN, 6);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_UNICODE_CI, 7);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_UNICODE_CI, 8);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_CHINESE_CI, 9);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_GB18030_BIN, 10);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UJIS_JAPANESE_CI, 11);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UJIS_BIN, 12);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_EUCKR_KOREAN_CI, 13);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_EUCKR_BIN, 14);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_CP932_JAPANESE_CI, 15);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_CP932_BIN, 16);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_EUCJPMS_JAPANESE_CI, 17);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_EUCJPMS_BIN, 18);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_GERMAN1_CI, 19);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_LATIN1_SWEDISH_CI, 20);

} // end sql
} // end oceanbase