/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include "ob_expr_str_cmp_func_common.ipp"

namespace oceanbase
{
namespace sql
{
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_PERSIAN_UCA_CI, 63);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_ESPERANTO_UCA_CI, 64);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_HUNGARIAN_UCA_CI, 65);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_SINHALA_UCA_CI, 66);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_GERMAN2_UCA_CI, 67);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_CROATIAN_UCA_CI, 68);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_UNICODE_520_CI, 69);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF8MB4_VIETNAMESE_CI, 70);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_ICELANDIC_UCA_CI, 71);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_LATVIAN_UCA_CI, 72);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_ROMANIAN_UCA_CI, 73);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SLOVENIAN_UCA_CI, 74);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_POLISH_UCA_CI, 75);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_ESTONIAN_UCA_CI, 76);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SPANISH_UCA_CI, 77);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SWEDISH_UCA_CI, 78);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_TURKISH_UCA_CI, 79);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_CZECH_UCA_CI, 80);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_DANISH_UCA_CI, 81);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_LITHUANIAN_UCA_CI, 82);
DEF_COMPILE_STR_FUNC_INIT(CS_TYPE_UTF16_SLOVAK_UCA_CI, 83);

} // end sql
} // end oceanbase