
--disable_warnings
drop table if exists t_h3_01_20;
drop table if exists t_h3_05_24;
drop table if exists t_h3_09_28;
drop table if exists t_h5_01_20;
drop table if exists t_h5_05_24;
drop table if exists t_h5_09_28;
drop table if exists t_r4_01_20;
drop table if exists t_r4_05_24;
drop table if exists t_r4_09_28;
drop table if exists t_r5_01_20;
drop table if exists t_r5_05_24;
drop table if exists t_r5_09_28;
drop table if exists t_h3_r4_01_20;
drop table if exists t_h3_r5_09_28;
drop table if exists t_h5_r4_01_20;
drop table if exists t_h5_r5_09_28;

drop table if exists t_refered;
drop table if exists t_h5_int;
drop table if exists t_r4_int;
drop table if exists t_r4_date;
drop table if exists t_r4_datetime;
drop table if exists t_r4_timestamp;
drop table if exists t_h5_r4_int_int;
drop table if exists t_h5_r4_int_int_datetime;


drop table if exists t_r4_h2_date_int;
drop table if exists t_r4_h3_date_int;
drop table if exists t_r4_h3_date_bigint;
drop table if exists tt;

drop table if exists t_many_range_part;

--enable_warnings
