/**
 * Copyright (c) 2021 OceanBase
 * OceanBase CE is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#ifndef OCEANBASE_STORAGE_SSTABLE_COPY_CHAIN_UTILS_
#define OCEANBASE_STORAGE_SSTABLE_COPY_CHAIN_UTILS_

#include "storage/ob_i_table.h"
#include "share/scheduler/ob_tenant_dag_scheduler.h"

namespace oceanbase
{
namespace storage
{
class ObSSTableCopyFinishTask;
class ObTabletCopyFinishTask;

// Sstable types copied by the tablet copy chain drivers (migration / restore).
// The copy table key array is sorted by snapshot version and scanned once with a
// single cursor; every key in it must be one of these types, anything else is an error.
inline bool is_ha_copy_sstable_type(const ObITable::TableType table_type)
{
  return ObITable::is_mds_sstable(table_type)
      || ObITable::is_minor_sstable(table_type)
      || ObITable::is_major_sstable(table_type)
      || ObITable::is_ddl_dump_sstable(table_type);
}

// Per-path scan filter of ObSSTableCopyChainScanner: whether the sstable needs to
// be copied. Restore skips the sstable types that the restore action does not need;
// both paths skip the sstables the local replica already contains.
class ObISSTableCopyScanPolicy
{
public:
  ObISSTableCopyScanPolicy() {}
  virtual ~ObISSTableCopyScanPolicy() {}
  virtual int check_need_copy_sstable(const ObITable::TableKey &table_key, bool &need_copy) = 0;
};

// Shared cursor scanner of the tablet copy chain drivers: rolls next_index forward
// over the snapshot-version-sorted copy table key array to the next sstable that
// the scan policy says still needs copy.
struct ObSSTableCopyChainScanner
{
  // Single source of truth for "which keys are legal in a copy table key array": a key
  // must be valid and one of the ha-copy sstable types, otherwise it is a bug. Both the
  // lazy scan below and the eager precheck (ObTabletRestoreTask::precheck_remote_sstable_exist_)
  // call it, so a new allowed type / changed rule never drifts between the two paths.
  static int validate_copy_table_key(const ObITable::TableKey &copy_table_key);
  // Validate one key (validate_copy_table_key) and ask the scan policy whether it still
  // needs copy.
  static int check_one_key(
      const ObITable::TableKey &copy_table_key,
      ObISSTableCopyScanPolicy &scan_policy,
      bool &need_copy);
  // found == false means the scan is exhausted, no more sstable to copy
  static int find_next_copy_table_key(
      const common::ObIArray<ObITable::TableKey> &copy_table_key_array,
      ObISSTableCopyScanPolicy &scan_policy,
      int64_t &next_index,
      bool &found);
};

// One unit of work generated by a driver round. By default a unit is the copy chain of one
// single sstable (consumed_count_ == 1, no batch keys). A path may instead report a batch unit:
// a run of consecutive sstables of the copy table key array that it can copy inline in one task
// (see ObBatchSSTableCopyTaskGenerator for the migration CG batch copy). consumed_count_ is how
// many array positions the unit covers -- it can be larger than batch_keys_.count(), because the
// positions of the sstables the local replica already contains are consumed (skipped) as well.
struct ObSSTableCopyUnit
{
  explicit ObSSTableCopyUnit(const uint64_t tenant_id);
  void reset();
  bool is_batch() const { return batch_keys_.count() > 0; }
  TO_STRING_KV(K_(consumed_count), "batch_key_count", batch_keys_.count());

  int64_t consumed_count_;
  common::ObArray<ObITable::TableKey> batch_keys_;
};

// How the copy chain of one sstable is wired between the parent task and the child task.
enum ObSSTableCopyTopology
{
  COPY_MACRO_BLOCKS = 0, // parent -> physical copy -> sstable finish -> child
  DIRECT_TO_FINISH,      // parent -> sstable finish -> child
  START_THEN_FINISH,     // parent -> sstable copy start -> sstable finish -> child
  BYPASS_TO_NEXT,        // parent -> child, no chain is built (e.g. src tablet does not exist)
};

// Shared DAG wiring of the tablet copy chains: builds the chain of one sstable
// between parent_task and child_task according to the topology.
struct ObSSTableCopyChainBuilder
{
  // finish_task must be already inited and is ignored for BYPASS_TO_NEXT;
  // newly created tasks are added into the dag
  static int build_sstable_copy_chain(
      share::ObIDag *dag,
      share::ObITask *parent_task,
      share::ObITask *child_task,
      ObSSTableCopyFinishTask *finish_task,
      const ObSSTableCopyTopology topology);
};

// Path-specific operations of the tablet copy chain driver. The driver skeleton
// (ObTabletCopyChainDriverTaskBase: process / roll to next key / hang the sink) is
// path-independent and lives in one place; everything that differs between migration
// and restore -- the ctx type, the failed-check, the per-sstable copy chain wiring,
// and the copy filter -- is collected behind this interface. The ops object only holds
// pointers set at driver init (ctx / finish task / src), so it is cheap to embed by
// value in each driver task and share unchanged across the whole driver chain.
class ObITabletCopyChainDriverOps : public ObISSTableCopyScanPolicy
{
public:
  ObITabletCopyChainDriverOps() {}
  virtual ~ObITabletCopyChainDriverOps() {}
  // the snapshot-version-sorted key array the scanner rolls over
  virtual const common::ObIArray<ObITable::TableKey> &get_copy_table_key_array() const = 0;
  // whether the owning dag / dag-net ctx has already failed
  virtual bool is_ctx_failed() const = 0;
  // build the copy chain of one sstable between parent_task and child_task
  // (prepare init param -> choose topology -> ObSSTableCopyChainBuilder)
  virtual int generate_physical_task(
      share::ObIDag *dag,
      ObTabletCopyFinishTask *tablet_copy_finish_task,
      const ObITable::TableKey &copy_table_key,
      share::ObITask *parent_task,
      share::ObITask *child_task) = 0;
  // Plan the unit of work of one driver round, starting at the sstable at start_index (which the
  // scanner already decided needs copy). The default is one single-sstable copy chain per round,
  // which is what the restore path uses; the migration path overrides it to batch a run of CG
  // sstables into one task. Only called with a start_index inside get_copy_table_key_array().
  virtual int plan_copy_unit(
      const int64_t start_index,
      ObSSTableCopyUnit &unit);
  // Wire the batch copy task of batch_keys between parent_task and child_task. Only called for
  // the batch units reported by plan_copy_unit, so the default implementation is unreachable.
  virtual int generate_batch_task(
      share::ObIDag *dag,
      ObTabletCopyFinishTask *tablet_copy_finish_task,
      const common::ObIArray<ObITable::TableKey> &batch_keys,
      share::ObITask *parent_task,
      share::ObITask *child_task);
  VIRTUAL_TO_STRING_KV(KP(this));
};

// Driver task that lazily generates the sstable copy chains of one tablet copy
// (migration or restore). Instead of pre-allocating one copy chain (each embedding a
// ~34KB ObSSTableCopyFinishTask) for every sstable up front, the driver rolls forward
// over the snapshot-version-sorted copy table key array and builds at most one chain
// per process() round, so at any time only one ObSSTableCopyFinishTask is alive in the
// dag. The chains are strictly serial: the next driver is the child of the current
// chain's finish task. The tablet copy finish task (sink) is always hung under the
// latest active driver, so its indegree never drops to 0 before the last driver
// finishes. This skeleton is shared by both paths; the path-specific behaviour is
// injected through ObITabletCopyChainDriverOps, supplied by the concrete subclass.
class ObTabletCopyChainDriverTaskBase : public share::ObITask
{
public:
  ObTabletCopyChainDriverTaskBase();
  virtual ~ObTabletCopyChainDriverTaskBase();
  virtual int process() override;
  VIRTUAL_TO_STRING_KV(KP(this), K_(is_inited), K_(next_index));
protected:
  // subclass calls this from its own init() once its ops object is set up
  int inner_init(
      ObITabletCopyChainDriverOps *ops,
      ObTabletCopyFinishTask *tablet_copy_finish_task,
      const int64_t next_index);
  // allocate the next driver (same concrete subclass) on the dag and init it with the
  // shared ctx pointers and the given cursor; the base only knows it as a base task
  virtual int alloc_and_init_next_driver_(
      const int64_t next_index,
      ObTabletCopyChainDriverTaskBase *&next_driver_task) = 0;
private:
  // build the copy tasks of the next copy unit (starting at copy_table_key_array_[next_index])
  // and hang the sink (tablet_copy_finish_task_) under a newly generated next driver
  int generate_next_sstable_chain_();
  // build the tasks of one planned unit between this driver and child_task: either the copy
  // chain of the single sstable at start_index, or the batch task of unit.batch_keys_
  int generate_copy_unit_tasks_(
      const ObSSTableCopyUnit &unit,
      const int64_t start_index,
      share::ObITask *child_task);
protected:
  bool is_inited_;
  ObITabletCopyChainDriverOps *ops_;                 // path-specific ops, embedded by the subclass
  ObTabletCopyFinishTask *tablet_copy_finish_task_;  // sink task of the tablet copy chains
  int64_t next_index_;                               // cursor into ops_->get_copy_table_key_array()
  DISALLOW_COPY_AND_ASSIGN(ObTabletCopyChainDriverTaskBase);
};

}
}
#endif
